services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
